### ISSUE TITLE
TMiniGameManager

### ISSUE THREAD

**Issue by ghost** [morsisko/SawmillBot#1]
FindPattern returns the wrong address, replace the pattern with

\xA1\x00\x00\x00\x00\x8B\x08\xFF\x51\x00\xA1\x00\x00\x00\x00\xE8\x00\x00\x00\x00\x33\xD2\xA1\x00\x00\x00\x00\xE8\x00\x00\x00\x00\x33\xD2\xA1\x00\x00\x00\x00\xE8\x00\x00\x00\x00\x33\xD2\xA1\x00\x00\x00\x00\xE8\x00\x00\x00\x00\x33\xD2

x????xxxx?x????x????xxx????x????xxx????x????xxx????x????xx

**Comment by morsisko** [comment]
Thanks, fixed
